In [1]:
pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 6.1 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 11.7 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [2]:
import pandas
from pymongo import MongoClient

In [3]:
client=MongoClient("mongodb+srv://praffull:mongodb913@sharayucluster.fib907c.mongodb.net/?appName=sharayucluster")

In [4]:
db=client["spiderdb"]

In [5]:
collfilms=db["films"]

In [6]:
data=list(collfilms.find())

**Load data**

In [7]:
df=pandas.DataFrame(data)
print(df)

    _id                filmnm category  releaseyr      written  \
0   151                sholay   action       1975  salim javed
1   152                    pk   comedy       2014          NaN
2   153            the matrix   action       1999          NaN
3   154         mughal e azam  romance       1960          NaN
4   155      mi5 rogue nation   action       2015          NaN
5   156                  maya  romance       1961          NaN
6   157     1942 a love story  romance       1994          NaN
7   158  chalti ka naam gaadi   comedy       1958          NaN
8   159             golmaal 3   comedy       2010          NaN
9   160                 bhoot   horror       2003          NaN
10  161               silsila  romance       1981          NaN
11  162                swades    drama       2004          NaN
12  163                  1917      war       2019          NaN

                 director             actor              actress  \
0            ramesh sippy  amitabh bachchan         jaya bhaduri
1         rajkumar hirani         amir khan       anushka sharma
2          wachowski bros      keanu reeves     carrie-anne moss
3                  k asif       dilip kumar            madhubala
4   christopher mcquarrie        tom cruise    rebeccca ferguson
5                     NaN         dev anand           mala sinha
6      vidhu vinod chopra       anil kapoor      manisha koirala
7             satyen bose     koshore kumar            madhubala
8            rohit shetty       ajay devgan  kareena kapoor khan
9         ram gopal verma               NaN     urmila matondkar
10            yash chopra  amitabh bachchan                rekha
11     ashutosh gowarikar    shah rukh khan                  NaN
12             sam mendes     george mackay                  NaN

              music     villain  budgetmn  collectionmn     comedian  \
0        r d burman  amjad khan      30.0         410.0          NaN
1               NaN         NaN     850.0        8540.0          NaN
2               NaN         NaN    4725.0       34950.0          NaN
3           naushad         NaN      15.0         110.0          NaN
4               NaN         NaN   11250.0       51225.0          NaN
5   salil choudhari         NaN       NaN           NaN          NaN
6        r d burman         NaN     257.0         896.0          NaN
7        s d burman   k n singh       NaN           NaN          NaN
8               NaN         NaN     350.0        1692.0  johny lever
9    salim sulaiman         NaN       NaN           NaN          NaN
10        shiv hari         NaN       NaN           NaN          NaN
11       a r rahman         NaN     250.0         380.0          NaN
12              NaN         NaN    7125.0       28875.0          NaN

   cinematography
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12  roger deakins

**Inspect data**

In [8]:
df.head(3)

,_id,filmnm,category,releaseyr,written,director,actor,actress,music,villain,budgetmn,collectionmn,comedian,cinematography
0,151,sholay,action,1975,salim javed,ramesh sippy,amitabh bachchan,jaya bhaduri,r d burman,amjad khan,30.0,410.0,NaN,NaN
1,152,pk,comedy,2014,NaN,rajkumar hirani,amir khan,anushka sharma,NaN,NaN,850.0,8540.0,NaN,NaN
2,153,the matrix,action,1999,NaN,wachowski bros,keanu reeves,carrie-anne moss,NaN,NaN,4725.0,34950.0,NaN,NaN

In [9]:
print(df.shape)

(13, 14)

In [10]:
print(df.columns)

Index(['_id', 'filmnm', 'category', 'releaseyr', 'written', 'director',
       'actor', 'actress', 'music', 'villain', 'budgetmn', 'collectionmn',
       'comedian', 'cinematography'],
      dtype='object')

In [11]:
print(df.dtypes)

_id                object
filmnm             object
category           object
releaseyr           int64
written            object
director           object
actor              object
actress            object
music              object
villain            object
budgetmn          float64
collectionmn      float64
comedian           object
cinematography     object
dtype: object

In [12]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   _id             13 non-null     object
 1   filmnm          13 non-null     object
 2   category        13 non-null     object
 3   releaseyr       13 non-null     int64
 4   written         1 non-null      object
 5   director        12 non-null     object
 6   actor           12 non-null     object
 7   actress         11 non-null     object
 8   music           8 non-null      object
 9   villain         2 non-null      object
 10  budgetmn        9 non-null      float64
 11  collectionmn    9 non-null      float64
 12  comedian        1 non-null      object
 13  cinematography  1 non-null      object
dtypes: float64(2), int64(1), object(11)
memory usage: 1.6+ KB
None

In [13]:
print(pandas.isnull(df))

      _id  filmnm  category  releaseyr  written  director  actor  actress  \
0   False   False     False      False    False     False  False    False
1   False   False     False      False     True     False  False    False
2   False   False     False      False     True     False  False    False
3   False   False     False      False     True     False  False    False
4   False   False     False      False     True     False  False    False
5   False   False     False      False     True      True  False    False
6   False   False     False      False     True     False  False    False
7   False   False     False      False     True     False  False    False
8   False   False     False      False     True     False  False    False
9   False   False     False      False     True     False   True    False
10  False   False     False      False     True     False  False    False
11  False   False     False      False     True     False  False     True
12  False   False     False      False     True     False  False     True

    music  villain  budgetmn  collectionmn  comedian  cinematography
0   False    False     False         False      True            True
1    True     True     False         False      True            True
2    True     True     False         False      True            True
3   False     True     False         False      True            True
4    True     True     False         False      True            True
5   False     True      True          True      True            True
6   False     True     False         False      True            True
7   False    False      True          True      True            True
8    True     True     False         False     False            True
9   False     True      True          True      True            True
10  False     True      True          True      True            True
11  False     True     False         False      True            True
12   True     True     False         False      True           False

In [14]:
df.isnull().sum()

_id                0
filmnm             0
category           0
releaseyr          0
written           12
director           1
actor              1
actress            2
music              5
villain           11
budgetmn           4
collectionmn       4
comedian          12
cinematography    12
dtype: int64

In [15]:
df.isnull().sum().sum()

np.int64(64)

**Handle missing values - remove rows with null values**

In [16]:
res=df.dropna()
print(res)

Empty DataFrame
Columns: [_id, filmnm, category, releaseyr, written, director, actor, actress, music, villain, budgetmn, collectionmn, comedian, cinematography]
Index: []

remove cols with null values

In [ ]:
res=df.dropna(axis=1)
print(res)

    _id                filmnm category  releaseyr
0   151                sholay   action       1975
1   152                    pk   comedy       2014
2   153            the matrix   action       1999
3   154         mughal e azam  romance       1960
4   155      mi5 rogue nation   action       2015
5   156                  maya  romance       1961
6   157     1942 a love story  romance       1994
7   158  chalti ka naam gaadi   comedy       1958
8   159             golmaal 3   comedy       2010
9   160                 bhoot   horror       2003
10  161               silsila  romance       1981
11  162                swades    drama       2004
12  163                  1917      war       2019

In [ ]:
df['actor'].fillna('unknown',inplace=True)
print(df)

    _id                filmnm category  releaseyr      written  \
0   151                sholay   action       1975  salim javed
1   152                    pk   comedy       2014          NaN
2   153            the matrix   action       1999          NaN
3   154         mughal e azam  romance       1960          NaN
4   155      mi5 rogue nation   action       2015          NaN
5   156                  maya  romance       1961          NaN
6   157     1942 a love story  romance       1994          NaN
7   158  chalti ka naam gaadi   comedy       1958          NaN
8   159             golmaal 3   comedy       2010          NaN
9   160                 bhoot   horror       2003          NaN
10  161               silsila  romance       1981          NaN
11  162                swades    drama       2004          NaN
12  163                  1917      war       2019          NaN

                 director             actor              actress  \
0            ramesh sippy  amitabh bachchan         jaya bhaduri
1         rajkumar hirani         amir khan       anushka sharma
2          wachowski bros      keanu reeves     carrie-anne moss
3                  k asif       dilip kumar            madhubala
4   christopher mcquarrie        tom cruise    rebeccca ferguson
5                     NaN         dev anand           mala sinha
6      vidhu vinod chopra       anil kapoor      manisha koirala
7             satyen bose     koshore kumar            madhubala
8            rohit shetty       ajay devgan  kareena kapoor khan
9         ram gopal verma           unknown     urmila matondkar
10            yash chopra  amitabh bachchan                rekha
11     ashutosh gowarikar    shah rukh khan                  NaN
12             sam mendes     george mackay                  NaN

              music     villain  budgetmn  collectionmn     comedian  \
0        r d burman  amjad khan      30.0         410.0          NaN
1               NaN         NaN     850.0        8540.0          NaN
2               NaN         NaN    4725.0       34950.0          NaN
3           naushad         NaN      15.0         110.0          NaN
4               NaN         NaN   11250.0       51225.0          NaN
5   salil choudhari         NaN       NaN           NaN          NaN
6        r d burman         NaN     257.0         896.0          NaN
7        s d burman   k n singh       NaN           NaN          NaN
8               NaN         NaN     350.0        1692.0  johny lever
9    salim sulaiman         NaN       NaN           NaN          NaN
10        shiv hari         NaN       NaN           NaN          NaN
11       a r rahman         NaN     250.0         380.0          NaN
12              NaN         NaN    7125.0       28875.0          NaN

   cinematography
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12  roger deakins

/tmp/ipykernel_4734/896115560.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['actor'].fillna('unknown',inplace=True)

In [ ]:
res=df.dropna(axis=1)
print(res)

    _id                filmnm category  releaseyr             actor
0   151                sholay   action       1975  amitabh bachchan
1   152                    pk   comedy       2014         amir khan
2   153            the matrix   action       1999      keanu reeves
3   154         mughal e azam  romance       1960       dilip kumar
4   155      mi5 rogue nation   action       2015        tom cruise
5   156                  maya  romance       1961         dev anand
6   157     1942 a love story  romance       1994       anil kapoor
7   158  chalti ka naam gaadi   comedy       1958     koshore kumar
8   159             golmaal 3   comedy       2010       ajay devgan
9   160                 bhoot   horror       2003           unknown
10  161               silsila  romance       1981  amitabh bachchan
11  162                swades    drama       2004    shah rukh khan
12  163                  1917      war       2019     george mackay

In [17]:
data={'Name':['Jos','Joe','Ben','Steve',None,'Pat','Joe'],
      'Age':[34,32,None,34,None,None,32]}
df=pandas.DataFrame(data)
print(df)

    Name   Age
0    Jos  34.0
1    Joe  32.0
2    Ben   NaN
3  Steve  34.0
4   None   NaN
5    Pat   NaN
6    Joe  32.0

**Remove duplicate rows**

In [18]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [21]:
df=df.drop_duplicates()
print(df)

    Name   Age
0    Jos  34.0
1    Joe  32.0
2    Ben   NaN
3  Steve  34.0
4   None   NaN
5    Pat   NaN

In [23]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
print(df)

    Name        Age
0    Jos  34.000000
1    Joe  32.000000
2    Ben  33.333333
3  Steve  34.000000
4   None  33.333333
5    Pat  33.333333

**Fix the datatypes**

In [24]:
df['Age']=df['Age'].astype(int)
print(df)

    Name  Age
0    Jos   34
1    Joe   32
2    Ben   33
3  Steve   34
4   None   33
5    Pat   33

**Renaming columns**

In [26]:
df=pandas.read_pickle("mobilestock")
print(df.head(3))

   S.No    Brand        Model Name           Color  RAM (GB)  ROM (GB)  \
0     1  Samsung  Galaxy S24 Ultra  Titanium Black        12       256
1     2  Samsung       Galaxy S24+   Cobalt Violet        12       256
2     3  Samsung        Galaxy S24     Marble Gray         8       128

            Processor  Screen Size (inches)  Price (INR)
0  Snapdragon 8 Gen 3                   6.8     124999.0
1  Snapdragon 8 Gen 3                   6.7      99999.0
2  Snapdragon 8 Gen 3                   6.2      74999.0

In [28]:
df.rename(columns={"RAM (GB)":"RAM","Screen Size (inches)":"Screen","Price (INR)":"Price"},inplace=True)
print(df.columns)

Index(['S.No', 'Brand', 'Model Name', 'Color', 'RAM', 'ROM (GB)', 'Processor',
       'Screen', 'Price'],
      dtype='object')

**Handle strings**

In [29]:
df['Model Name']=df['Model Name'].str.strip()
df['Brand']=df['Brand'].str.lower()
print(df.head())

   S.No    Brand        Model Name            Color  RAM  ROM (GB)  \
0     1  samsung  Galaxy S24 Ultra   Titanium Black   12       256
1     2  samsung       Galaxy S24+    Cobalt Violet   12       256
2     3  samsung        Galaxy S24      Marble Gray    8       128
3     4  samsung        Galaxy A55     Awesome Navy    8       128
4     5  samsung        Galaxy A35  Awesome Iceblue    6       128

            Processor  Screen     Price
0  Snapdragon 8 Gen 3     6.8  124999.0
1  Snapdragon 8 Gen 3     6.7   99999.0
2  Snapdragon 8 Gen 3     6.2   74999.0
3         Exynos 1480     6.6   38999.0
4         Exynos 1380     6.6   30999.0

**Handle inconsistent values**

In [31]:
lst=[
    ['praffull','male'],
    ['sharayu','f'],
    ['shailaja','female'],
    ['megha','female'],
    ['soham','m']
]
df=pandas.DataFrame(lst)
print(df)

          0       1
0  praffull    male
1   sharayu       f
2  shailaja  female
3     megha  female
4     soham       m

In [32]:
df[1]=df[1].replace({
    "M":"Male","m":"Male","male":"Male",
    "F":"Female","f":"Female","female":"Female"
})
print(df)

          0       1
0  praffull    Male
1   sharayu  Female
2  shailaja  Female
3     megha  Female
4     soham    Male

**handling dates - later**

**Drop unwanted rows and columns**

In [36]:
df=pandas.read_pickle("mobilestock")
print(df.head(3))
print(df.shape)

   S.No    Brand        Model Name           Color  RAM (GB)  ROM (GB)  \
0     1  Samsung  Galaxy S24 Ultra  Titanium Black        12       256
1     2  Samsung       Galaxy S24+   Cobalt Violet        12       256
2     3  Samsung        Galaxy S24     Marble Gray         8       128

            Processor  Screen Size (inches)  Price (INR)
0  Snapdragon 8 Gen 3                   6.8     124999.0
1  Snapdragon 8 Gen 3                   6.7      99999.0
2  Snapdragon 8 Gen 3                   6.2      74999.0
(50, 9)

In [42]:
res=df[df['RAM (GB)']>10]
print(res.shape)
print(res)

(21, 9)
    S.No     Brand          Model Name            Color  RAM (GB)  ROM (GB)  \
0      1   Samsung    Galaxy S24 Ultra   Titanium Black        12       256
1      2   Samsung         Galaxy S24+    Cobalt Violet        12       256
13    14   OnePlus                  12      Silky Black        12       256
17    18   OnePlus                Open     Emerald Dusk        16       512
18    19    Xiaomi            14 Ultra            White        16       512
19    20    Xiaomi                  14            Black        12       256
20    21    Xiaomi              13 Pro    Ceramic Black        12       256
21    22    Xiaomi  Redmi Note 13 Pro+     Fusion White        12       256
25    26      Vivo            X100 Pro   Asteroid Black        16       512
26    27      Vivo                X100   Startrail Blue        12       256
27    28      Vivo             V30 Pro    Peacock Green        12       256
30    31      OPPO         Find X7 Pro    Desert Silver        16       512
31    32      OPPO         Reno 12 Pro    Nebula Silver        12       256
35    36    Realme                GT 6     Fluid Silver        12       256
38    39    Realme             12+ Pro  Navigator Beige        12       256
40    41  Motorola         Edge 50 Pro     Black Beauty        12       256
45    46   Nothing            Phone 2a            Black        12       256
46    47   Nothing             Phone 2            White        12       256
47    48      iQOO                  12           Legend        16       256
48    49      iQOO           Neo 9 Pro        Fiery Red        12       256
49    50    Google         Pixel 8 Pro         Obsidian        12       128

                Processor  Screen Size (inches)  Price (INR)
0      Snapdragon 8 Gen 3                  6.80     124999.0
1      Snapdragon 8 Gen 3                  6.70      99999.0
13     Snapdragon 8 Gen 3                  6.82      64999.0
17     Snapdragon 8 Gen 2                  7.82     139999.0
18     Snapdragon 8 Gen 3                  6.73      99999.0
19     Snapdragon 8 Gen 3                  6.36      69999.0
20     Snapdragon 8 Gen 2                  6.73      79999.0
21   Dimensity 7200 Ultra                  6.67      31999.0
25         Dimensity 9300                  6.78      89999.0
26         Dimensity 9300                  6.78      63999.0
27     Snapdragon 7 Gen 3                  6.78      44999.0
30     Snapdragon 8 Gen 3                  6.82      89999.0
31  Dimensity 7300 Energy                  6.70      36999.0
35    Snapdragon 8s Gen 3                  6.78      39999.0
38         Dimensity 7050                  6.67      27999.0
40     Snapdragon 7 Gen 3                  6.70      31999.0
45     Dimensity 7200 Pro                  6.70      23999.0
46    Snapdragon 8+ Gen 1                  6.70      44999.0
47     Snapdragon 8 Gen 3                  6.78      52999.0
48     Snapdragon 8 Gen 2                  6.78      36999.0
49       Google Tensor G3                  6.70     106999.0

In [40]:
res=df.drop(columns=['S.No','Color','Processor'])
print(res.head(3))

     Brand        Model Name  RAM (GB)  ROM (GB)  Screen Size (inches)  \
0  Samsung  Galaxy S24 Ultra        12       256                   6.8
1  Samsung       Galaxy S24+        12       256                   6.7
2  Samsung        Galaxy S24         8       128                   6.2

   Price (INR)
0     124999.0
1      99999.0
2      74999.0

In [43]:
res=df[df['RAM (GB)']>10]
print(res.shape)
res.reset_index(drop=True,inplace=True)
print(res)

(21, 9)
    S.No     Brand          Model Name            Color  RAM (GB)  ROM (GB)  \
0      1   Samsung    Galaxy S24 Ultra   Titanium Black        12       256
1      2   Samsung         Galaxy S24+    Cobalt Violet        12       256
2     14   OnePlus                  12      Silky Black        12       256
3     18   OnePlus                Open     Emerald Dusk        16       512
4     19    Xiaomi            14 Ultra            White        16       512
5     20    Xiaomi                  14            Black        12       256
6     21    Xiaomi              13 Pro    Ceramic Black        12       256
7     22    Xiaomi  Redmi Note 13 Pro+     Fusion White        12       256
8     26      Vivo            X100 Pro   Asteroid Black        16       512
9     27      Vivo                X100   Startrail Blue        12       256
10    28      Vivo             V30 Pro    Peacock Green        12       256
11    31      OPPO         Find X7 Pro    Desert Silver        16       512
12    32      OPPO         Reno 12 Pro    Nebula Silver        12       256
13    36    Realme                GT 6     Fluid Silver        12       256
14    39    Realme             12+ Pro  Navigator Beige        12       256
15    41  Motorola         Edge 50 Pro     Black Beauty        12       256
16    46   Nothing            Phone 2a            Black        12       256
17    47   Nothing             Phone 2            White        12       256
18    48      iQOO                  12           Legend        16       256
19    49      iQOO           Neo 9 Pro        Fiery Red        12       256
20    50    Google         Pixel 8 Pro         Obsidian        12       128

                Processor  Screen Size (inches)  Price (INR)
0      Snapdragon 8 Gen 3                  6.80     124999.0
1      Snapdragon 8 Gen 3                  6.70      99999.0
2      Snapdragon 8 Gen 3                  6.82      64999.0
3      Snapdragon 8 Gen 2                  7.82     139999.0
4      Snapdragon 8 Gen 3                  6.73      99999.0
5      Snapdragon 8 Gen 3                  6.36      69999.0
6      Snapdragon 8 Gen 2                  6.73      79999.0
7    Dimensity 7200 Ultra                  6.67      31999.0
8          Dimensity 9300                  6.78      89999.0
9          Dimensity 9300                  6.78      63999.0
10     Snapdragon 7 Gen 3                  6.78      44999.0
11     Snapdragon 8 Gen 3                  6.82      89999.0
12  Dimensity 7300 Energy                  6.70      36999.0
13    Snapdragon 8s Gen 3                  6.78      39999.0
14         Dimensity 7050                  6.67      27999.0
15     Snapdragon 7 Gen 3                  6.70      31999.0
16     Dimensity 7200 Pro                  6.70      23999.0
17    Snapdragon 8+ Gen 1                  6.70      44999.0
18     Snapdragon 8 Gen 3                  6.78      52999.0
19     Snapdragon 8 Gen 2                  6.78      36999.0
20       Google Tensor G3                  6.70     106999.0

**Final Verification**

In [46]:
print(df.isnull().sum().sum())
print(df.duplicated().sum())

0
0